package com.example.tomas.hadzana;

public class Constants {
    public Constants() {

    }

    public static final Integer FIRST_NAME = 0;
    public static final Integer SECOND_NAME = 1;
    public static final Integer NUMBER = 2;
    public static final Integer COUNT_GOAL_ON_TARGET = 3;
    public static final Integer COUNT_SHOT_MISS = 4;
    public static final Integer COUNT_SHOT_GOALKEEPER = 5;
    public static final Integer COUNT_MISS_BALL = 6;
    public static final Integer COUNT_REACH_FAUL_SHOT = 7;
    public static final Integer COUNT_PLUS = 8;
    public static final Integer COUNT_MINUS = 9;
    public static final Integer COUNT_FAUL = 10;
    public static final Integer COUNT_YELLOW_CARD = 11;
    public static final Integer COUNT_RED_CARD = 12;
    public static final Integer COUNT_REACH_BALL = 13;
    public static final Integer COUNT_FAUL_SHOT_GOAL = 14;
    public static final Integer COUNT_FAUL_SHOT_MISS = 15;
    public static final Integer COUNT_BREJK_GOAL = 16;
    public static final Integer COUNT_BREJK_MISS = 17;
    public static final Integer COUNT_GOAL_WING = 18;
    public static final Integer COUNT_MISS_WING = 19;
    public static final Integer COUNT_GOAL_6M = 20;
    public static final Integer COUNT_GOAL_7M = 21;
    public static final Integer COUNT_GOAL_9M = 22;
    public static final Integer COUNT_MISS_6M = 23;
    public static final Integer COUNT_MISS_7M = 24;
    public static final Integer COUNT_MISS_9M = 25;
    public static final Integer COUNT_CATCH_BY_GOALKEEPER_BREJK = 26;
    public static final Integer COUNT_CATCH_BY_GOALKEEPER_WING = 27;
    public static final Integer COUNT_CATCH_BY_GOALKEEPER_6M = 28;
    public static final Integer COUNT_CATCH_BY_GOALKEEPER_7M = 29;
    public static final Integer COUNT_CATCH_BY_GOALKEEPER_9M = 30;
    public static final Integer COUNT_PLAYERS_TIME_ON_PLAYGROUND = 31;
    public static final Integer SHOTS_PREDICTION = 32;
    public static final Integer SHOTS_PREDICTION_BREJK = 33;
    public static final Integer SHOTS_PREDICTION_WING = 34;
    public static final Integer SHOTS_PREDICTION_6M = 35;
    public static final Integer SHOTS_PREDICTION_7M = 36;
    public static final Integer SHOTS_PREDICTION_9M = 37;
    public static final Integer FAUL_SHOTS_PREDICTION = 38;
    public static final Integer EFFICIENT_IN_DEFENSIVE = 39;
    public static final Integer COUNT_OF_PLAYED_GAMES = 40;
    public static final Integer EXPLOITATION = 41;
    public static final Integer PRIMARY_POSITION = 42;
    public static final Integer SECONDARY_POSITION = 43;
    public static final Integer BIRTH_DATE = 44;
    public static final Integer SOCIAL_SECURITY_NUMBER = 45;
    public static final Integer GENDER = 46;
    public static final Integer NOTE = 47;
    public static final Integer VALUES_CHANGE = 48;
    public static final Integer PRIMARY_KEY_FOR_PLAYER = 49;
    public static final Integer TURNAMENT_PK_ROSTER = 50;

    public static final Integer PLAYER_FIRST_NAME = 0;
    public static final Integer PLAYER_SECOND_NAME = 1;
    public static final Integer PLAYER_NUMBER = 2;
    public static final Integer GOAL_ON_TARGET = 3;
    public static final Integer SHOT_MISS = 4;
    public static final Integer SHOT_GOALKEEPER = 5;
    public static final Integer MISS_BALL = 6;
    public static final Integer REACH_FAUL_SHOT = 7;
    public static final Integer PLUS = 8;
    public static final Integer MINUS = 9;
    public static final Integer FAUL = 10;
    public static final Integer YELLOW_CARD = 11;
    public static final Integer RED_CARD = 12;
    public static final Integer REACH_BALL = 13;
    public static final Integer FAUL_SHOT_GOAL = 14;
    public static final Integer FAUL_SHOT_MISS = 15;
    public static final Integer BREJK_GOAL = 16;
    public static final Integer BREJK_MISS = 17;
    public static final Integer GOAL_WING = 18;
    public static final Integer MISS_WING = 19;
    public static final Integer GOAL_6M = 20;
    public static final Integer GOAL_7M = 21;
    public static final Integer GOAL_9M = 22;
    public static final Integer MISS_6M = 23;
    public static final Integer MISS_7M = 24;
    public static final Integer MISS_9M = 25;
    public static final Integer CATCH_BY_GOALKEEPER_BREJK = 26;
    public static final Integer CATCH_BY_GOALKEEPER_WING = 27;
    public static final Integer CATCH_BY_GOALKEEPER_6M = 28;
    public static final Integer CATCH_BY_GOALKEEPER_7M = 29;
    public static final Integer CATCH_BY_GOALKEEPER_9M = 30;
    public static final Integer PLAYERS_TIME_ON_PLAYGROUND = 31;
    public static final Integer SHOTS_PREDICTION_FOR_GAME = 32;
    public static final Integer SHOTS_PREDICTION_BREJK_FOR_GAME = 33;
    public static final Integer SHOTS_PREDICTION_WING_FOR_GAME = 34;
    public static final Integer SHOTS_PREDICTION_6M_FOR_GAME = 35;
    public static final Integer SHOTS_PREDICTION_7M_FOR_GAME = 36;
    public static final Integer SHOTS_PREDICTION_9M_FOR_GAME = 37;
    public static final Integer FAUL_SHOTS_PREDICTION_FOR_GAME = 38;
    public static final Integer EFFICIENT_IN_DEFENSIVE_FOR_GAME = 39;
    public static final Integer VALUES_ARE_CONVERTED_PLAYER = 40;
    public static final Integer TURNAMENT_PLAYER_PK = 41;

    public static final Integer HISTORY_PLAYER_FIRST_NAME = 0;
    public static final Integer HISTORY_PLAYER_SECOND_NAME = 1;
    public static final Integer HISTORY_PLAYER_NUMBER = 2;
    public static final Integer HISTORY_GOAL_ON_TARGET = 3;
    public static final Integer HISTORY_SHOT_MISS = 4;
    public static final Integer HISTORY_SHOT_GOALKEEPER = 5;
    public static final Integer HISTORY_MISS_BALL = 6;
    public static final Integer HISTORY_REACH_FAUL_SHOT = 7;
    public static final Integer HISTORY_PLUS = 8;
    public static final Integer HISTORY_MINUS = 9;
    public static final Integer HISTORY_FAUL = 10;
    public static final Integer HISTORY_YELLOW_CARD = 11;
    public static final Integer HISTORY_RED_CARD = 12;
    public static final Integer HISTORY_REACH_BALL = 13;
    public static final Integer HISTORY_FAUL_SHOT_GOAL = 14;
    public static final Integer HISTORY_FAUL_SHOT_MISS = 15;
    public static final Integer HISTORY_BREJK_GOAL = 16;
    public static final Integer HISTORY_BREJK_MISS = 17;
    public static final Integer HISTORY_GOAL_WING = 18;
    public static final Integer HISTORY_MISS_WING = 19;
    public static final Integer HISTORY_GOAL_6M = 20;
    public static final Integer HISTORY_GOAL_7M = 21;
    public static final Integer HISTORY_GOAL_9M = 22;
    public static final Integer HISTORY_MISS_6M = 23;
    public static final Integer HISTORY_MISS_7M = 24;
    public static final Integer HISTORY_MISS_9M = 25;
    public static final Integer HISTORY_CATCH_BY_GOALKEEPER_BREJK = 26;
    public static final Integer HISTORY_CATCH_BY_GOALKEEPER_WING = 27;
    public static final Integer HISTORY_CATCH_BY_GOALKEEPER_6M = 28;
    public static final Integer HISTORY_CATCH_BY_GOALKEEPER_7M = 29;
    public static final Integer HISTORY_CATCH_BY_GOALKEEPER_9M = 30;
    public static final Integer HISTORY_PLAYERS_TIME_ON_PLAYGROUND = 31;
    public static final Integer HISTORY_SHOTS_PREDICTION = 32;
    public static final Integer HISTORY_SHOTS_PREDICTION_BREJK = 33;
    public static final Integer HISTORY_SHOTS_PREDICTION_WING = 34;
    public static final Integer HISTORY_SHOTS_PREDICTION_6M = 35;
    public static final Integer HISTORY_SHOTS_PREDICTION_7M = 36;
    public static final Integer HISTORY_SHOTS_PREDICTION_9M = 37;
    public static final Integer HISTORY_FAUL_SHOTS_PREDICTION = 38;
    public static final Integer HISTORY_EFFICIENT_IN_DEFENSIVE = 39;
    public static final Integer HISTORY_DATETIME_PLAYER = 41;
    public static final Integer TURNAMENT_HISTORY_PLAYER_PK = 42;

    public static final Integer GOALKEEPER_FIRST_NAME_ROSTER = 0;
    public static final Integer GOALKEEPER_SECOND_NAME_ROSTER = 1;
    public static final Integer GOALKEEPER_NUMBER_ROSTER = 2;
    public static final Integer COUNT_CATCH = 3;
    public static final Integer COUNT_PASS_LONG_GOOD = 4;
    public static final Integer COUNT_PASS_LONG_BAD = 5;
    public static final Integer COUNT_PASS_SHORT_GOOD = 6;
    public static final Integer COUNT_PASS_SHORT_BAD = 7;
    public static final Integer COUNT_CATCH_FAUL_SHOT = 8;
    public static final Integer COUNT_MISS_FAUL_SHOT = 9;
    public static final Integer COUNT_RECOVERED_GOALS = 10;
    public static final Integer COUNT_BREJK_CATCH = 11;
    public static final Integer COUNT_BREJK_RECOVERED = 12;
    public static final Integer COUNT_WING_CATCH = 13;
    public static final Integer COUNT_WING_RECOVERED = 14;
    public static final Integer COUNT_CATCH_6M = 15;
    public static final Integer COUNT_CATCH_7M = 16;
    public static final Integer COUNT_CATCH_9M = 17;
    public static final Integer COUNT_RECOVERED_6M = 18;
    public static final Integer COUNT_RECOVERED_7M = 19;
    public static final Integer COUNT_RECOVERED_9M = 20;
    public static final Integer COUNT_FAUL_GOALKEEPER = 22;
    public static final Integer COUNT_YELLOW_CARD_GOALKEEPER = 22;
    public static final Integer COUNT_RED_CARD_GOALKEEPER = 23;
    public static final Integer PREDICTION_OF_CATCH = 24;
    public static final Integer PREDICTION_OF_CATCH_BREJK = 25;
    public static final Integer PREDICTION_OF_CATCH_WING = 26;
    public static final Integer PREDICTION_OF_CATCH_6M = 27;
    public static final Integer PREDICTION_OF_CATCH_7M = 28;
    public static final Integer PREDICTION_OF_CATCH_9M = 29;
    public static final Integer PREDICTION_OF_LONG_PASS = 30;
    public static final Integer PREDICTION_OF_SHORT_PASS = 31;
    public static final Integer PREDICTION_OF_CATCH_FAUL_SHOT = 32;
    public static final Integer COUNT_OF_PLAYED_GAMES_GOALKEEPER = 33;
    public static final Integer COUNT_OF_INTERVENTIONS = 34;
    public static final Integer COUNT_OF_TIME_ON_PLAYGROUND_GOALKEEPER = 35;
    public static final Integer GOALKEEPER_BIRTH_DATE = 36;
    public static final Integer GOALKEEPER_SOCIAL_SECURITY_NUMBER = 37;
    public static final Integer GOALKEEPER_GENDER = 38;
    public static final Integer GOALKEEPER_NOTE = 39;
    public static final Integer GOALKEEPER_VALUES_CHANGE = 40;
    public static final Integer GOALKEEPER_PRIMARY_KEY_ROSTER = 41;
    public static final Integer TURNAMENT_GOALKEEPER_PK_ROSTER = 42;

    public static final Integer GOALKEEPER_FIRST_NAME = 0;
    public static final Integer GOALKEEPER_SECOND_NAME = 1;
    public static final Integer GOALKEEPER_NUMBER = 2;
    public static final Integer CATCH = 3;
    public static final Integer PASS_LONG_GOOD = 4;
    public static final Integer PASS_LONG_BAD = 5;
    public static final Integer PASS_SHORT_GOOD = 6;
    public static final Integer PASS_SHORT_BAD = 7;
    public static final Integer CATCH_FAUL_SHOT = 8;
    public static final Integer MISS_FAUL_SHOT = 9;
    public static final Integer RECOVERED_GOALS = 10;
    public static final Integer BREJK_CATCH = 11;
    public static final Integer BREJK_RECOVERED = 12;
    public static final Integer WING_CATCH = 13;
    public static final Integer WING_RECOVERED = 14;
    public static final Integer CATCH_6M = 15;
    public static final Integer CATCH_7M = 16;
    public static final Integer CATCH_9M = 17;
    public static final Integer RECOVERED_6M = 18;
    public static final Integer RECOVERED_7M = 19;
    public static final Integer RECOVERED_9M = 20;
    public static final Integer FAUL_GOALKEEPER = 21;
    public static final Integer YELLOW_CARD_GOALKEEPER = 22;
    public static final Integer RED_CARD_GOALKEEPER = 23;
    public static final Integer PREDICTION_OF_CATCH_FOR_GAME = 24;
    public static final Integer PREDICTION_OF_CATCH_BREJK_FOR_GAME = 25;
    public static final Integer PREDICTION_OF_CATCH_WING_FOR_GAME = 26;
    public static final Integer PREDICTION_OF_CATCH_6M_FOR_GAME = 27;
    public static final Integer PREDICTION_OF_CATCH_7M_FOR_GAME = 28;
    public static final Integer PREDICTION_OF_CATCH_9M_FOR_GAME = 29;
    public static final Integer PREDICTION_OF_LONG_PASS_FOR_GAME = 30;
    public static final Integer PREDICTION_OF_SHORT_PASS_FOR_GAME = 31;
    public static final Integer PREDICTION_OF_CATCH_FAUL_SHOT_FOR_GAME = 32;
    public static final Integer COUNT_OF_INTERVENTIONS_FOR_GAME = 33;
    public static final Integer VALUES_ARE_COMVERTED_GOALKEEPER = 34;
    public static final Integer TIME_ON_PLAYGROUND_GOALKEEPER = 35;
    public static final Integer TURNAMENT_GOALKEEPER_PK = 36;

    public static final Integer HISTORY_GOALKEEPER_FIRST_NAME = 0;
    public static final Integer HISTORY_GOALKEEPER_SECOND_NAME = 1;
    public static final Integer HISTORY_GOALKEEPER_NUMBER = 2;
    public static final Integer HISTORY_CATCH = 3;
    public static final Integer HISTORY_PASS_LONG_GOOD = 4;
    public static final Integer HISTORY_PASS_LONG_BAD = 5;
    public static final Integer HISTORY_PASS_SHORT_GOOD = 6;
    public static final Integer HISTORY_PASS_SHORT_BAD = 7;
    public static final Integer HISTORY_CATCH_FAUL_SHOT = 8;
    public static final Integer HISTORY_MISS_FAUL_SHOT = 9;
    public static final Integer HISTORY_RECOVERED_GOALS = 10;
    public static final Integer HISTORY_BREJK_CATCH = 11;
    public static final Integer HISTORY_BREJK_RECOVERED = 12;
    public static final Integer HISTORY_WING_CATCH = 13;
    public static final Integer HISTORY_WING_RECOVERED = 14;
    public static final Integer HISTORY_CATCH_6M = 15;
    public static final Integer HISTORY_CATCH_7M = 16;
    public static final Integer HISTORY_CATCH_9M = 17;
    public static final Integer HISTORY_RECOVERED_6M = 18;
    public static final Integer HISTORY_RECOVERED_7M = 19;
    public static final Integer HISTORY_RECOVERED_9M = 20;
    public static final Integer HISTORY_FAUL_GOALKEEPER = 21;
    public static final Integer HISTORY_YELLOW_CARD_GOALKEEPER = 22;
    public static final Integer HISTORY_RED_CARD_GOALKEEPER = 23;
    public static final Integer HISTORY_PREDICTION_OF_CATCH = 24;
    public static final Integer HISTORY_PREDICTION_OF_CATCH_BREJK = 25;
    public static final Integer HISTORY_PREDICTION_OF_CATCH_WING = 26;
    public static final Integer HISTORY_PREDICTION_OF_CATCH_6M = 27;
    public static final Integer HISTORY_PREDICTION_OF_CATCH_7M = 28;
    public static final Integer HISTORY_PREDICTION_OF_CATCH_9M = 29;
    public static final Integer HISTORY_PREDICTION_OF_LONG_PASS = 30;
    public static final Integer HISTORY_PREDICTION_OF_SHORT_PASS = 31;
    public static final Integer HISTORY_PREDICTION_OF_CATCH_FAUL_SHOT = 32;
    public static final Integer HISTORY_COUNT_OF_INTERVENTIONS = 33;
    public static final Integer HISTORY_TIME_ON_PLAYGROUND_GOALKEEPER = 34;
    public static final Integer HISTORY_VALUES_ARE_CONVERTED_GOALKEEPER = 35;
    public static final Integer HISTORY_DATETIME_GOALKEEPER = 36;
    public static final Integer TURNAMENT_HISTORY_PK_GOALKEEPER = 37;

    public static final Integer TEAM_NAME = 0;
    public static final Integer NAME_OF_OPONENT = 1;
    public static final Integer HALF_TIME_SCORE = 2;
    public static final Integer FINAL_SCORE = 3;
    public static final Integer MATCH_TIME = 4;
    public static final Integer TIME_IN_OFENSIVE = 5;
    public static final Integer COUNT_OF_OFENSIVE = 6;
    public static final Integer TIME_IN_DEFENSIVE = 7;
    public static final Integer COUNT_OF_DEFENSIVE = 8;
    public static final Integer GAME_REPLAY = 9;
    public static final Integer GAME_REPORT = 10;
    public static final Integer POWERPLAYS_COUNT = 11;
    public static final Integer POWERPLAYS_WIN = 12;
    public static final Integer REACHED_GOAL_WHILE_POWERPLAY = 13;
    public static final Integer COUNT_OF_WEAKENING = 14;
    public static final Integer GOAL_WHILE_WEAKENING = 15;
    public static final Integer REACHED_GOAL_WHILE_WEAKENING = 16;
    public static final Integer GAME_COUNT_OF_SHOTS = 17;
    public static final Integer GAME_COUNT_OF_MISS_SHOTS = 18;
    public static final Integer GAME_COUNT_OF_GOALKEEPER_SHOTS = 19;
    public static final Integer GAME_COUNT_OF_MISS_BALLS = 20;
    public static final Integer GAME_COUNT_OF_FAUL_SHOTS = 21;
    public static final Integer GAME_COUNT_OF_PLUS = 22;
    public static final Integer GAME_COUNT_OF_MINUS = 23;
    public static final Integer GAME_COUNT_OF_FAULS = 24;
    public static final Integer GAME_COUNT_OF_YELLOW_CARDS = 25;
    public static final Integer GAME_COUNT_OF_RED_CARDS = 26;
    public static final Integer GAME_COUNT_OF_REACH_BALLS = 27;
    public static final Integer GAME_COUNT_OF_FAUL_SHOTS_GOAL = 28;
    public static final Integer GAME_COUNT_OF_FAUL_SHOTS_MISS = 29;
    public static final Integer GAME_COUNT_OF_GOAL_BREJK = 30;
    public static final Integer GAME_COUNT_OF_MISS_BREJK = 31;
    public static final Integer GAME_COUNT_OF_GOAL_WING = 32;
    public static final Integer GAME_COUNT_OF_MISS_WING = 33;
    public static final Integer GAME_COUNT_OF_GOAL_6M = 34;
    public static final Integer GAME_COUNT_OF_GOAL_7M = 35;
    public static final Integer GAME_COUNT_OF_GOAL_9M = 36;
    public static final Integer GAME_COUNT_OF_MISS_6M = 37;
    public static final Integer GAME_COUNT_OF_MISS_7M = 38;
    public static final Integer GAME_COUNT_OF_MISS_9M = 39;
    public static final Integer GAME_COUNT_OF_GOALKEEPER_BREJK = 40;
    public static final Integer GAME_COUNT_OF_GOALKEEPER_WING = 41;
    public static final Integer GAME_COUNT_OF_GOALKEEPER6_M = 42;
    public static final Integer GAME_COUNT_OF_GOALKEEPER_7M = 43;
    public static final Integer GAME_COUNT_OF_GOALKEEPER_9M = 44;
    public static final Integer GAME_PREDICTION_OF_SHOTS = 45;
    public static final Integer GAME_PREDICTION_OF_SHOTS_BREJK = 46;
    public static final Integer GAME_PREDICTION_OF_SHOTS_WING = 47;
    public static final Integer GAME_PREDICTION_OF_SHOTS_6M = 48;
    public static final Integer GAME_PREDICTION_OF_SHOTS_7M = 49;
    public static final Integer GAME_PREDICTION_OF_SHOTS_9M = 50;
    public static final Integer GAME_PREDICTION_OF_FAULS_SHOTS = 51;
    public static final Integer MATCH_SUCCESSFULLY_COMPLETED = 52;
    public static final Integer GAME_PLAYED_HOME = 53;
    public static final Integer DATETIME_PK_GAME = 54;
    public static final Integer PK_NUMBER_GAME = 55;
    public static final Integer TURNAMENT_GAME_PK = 56;

    public static final Integer SUMMARY_COUNT_WIN_GAMES = 0;
    public static final Integer SUMMARY_COUNT_WIN_GAMES_HOME = 1;
    public static final Integer SUMMARY_COUNT_WIN_GAMES_OUT = 2;
    public static final Integer SUMMARY_COUNT_LOSE_GAMES = 3;
    public static final Integer SUMMARY_COUNT_LOSE_GAMES_HOME = 4;
    public static final Integer SUMMARY_COUNT_LOSE_GAMES_OUT = 5;
    public static final Integer SUMMARY_COUNT_OF_OFENSIVE = 6;
    public static final Integer SUMMARY_COUNT_OF_DEFENSIVE = 7;
    public static final Integer SUMMARY_POWER_PLAYS_COUNT = 8;
    public static final Integer SUMMARY_POWER_PLAYS_WIN = 9;
    public static final Integer SUMMARY_REACHED_GOAL_WHILE_POWER_PLAY = 10;
    public static final Integer SUMMARY_COUNT_OF_WEAKENING = 11;
    public static final Integer SUMMARY_GOAL_WHILE_WEAKENING = 12;
    public static final Integer SUMMARY_REACHED_GOAL_WHILE_WEAKENING = 13;
    public static final Integer SUMMARY_GAME_COUNT_OF_SHOTS = 14;
    public static final Integer SUMMARY_GAME_COUNT_OF_MISS_SHOTS = 15;
    public static final Integer SUMMARY_GAME_COUNT_OF_GOALKEEPER_SHOTS = 16;
    public static final Integer SUMMARY_GAME_COUNT_OF_MISS_BALLS = 17;
    public static final Integer SUMMARY_GAME_COUNT_OF_FAUL_SHOTS = 18;
    public static final Integer SUMMARY_GAME_COUNT_OF_PLUS = 19;
    public static final Integer SUMMARY_GAME_COUNT_OF_MINUS = 20;
    public static final Integer SUMMARY_GAME_COUNT_OF_FAULS = 21;
    public static final Integer SUMMARY_GAME_COUNT_OF_YELLOW_CARDS = 22;
    public static final Integer SUMMARY_GAME_COUNT_OF_RED_CARDS = 23;
    public static final Integer SUMMARY_GAME_COUNT_OF_REACH_BALLS = 24;
    public static final Integer SUMMARY_GAME_COUNT_OF_FAUL_SHOTS_GOAL = 25;
    public static final Integer SUMMARY_GAME_COUNT_OF_FAUL_SHOTS_MISS = 26;
    public static final Integer SUMMARY_GAME_COUNT_OF_GOAL_BREJK = 27;
    public static final Integer SUMMARY_GAME_COUNT_OF_MISS_BREJK = 28;
    public static final Integer SUMMARY_GAME_COUNT_OF_GOAL_WING = 29;
    public static final Integer SUMMARY_GAME_COUNT_OF_MISS_WING = 30;
    public static final Integer SUMMARY_GAME_COUNT_OF_GOAL_6M = 31;
    public static final Integer SUMMARY_GAME_COUNT_OF_GOAL_7M = 32;
    public static final Integer SUMMARY_GAME_COUNT_OF_GOAL_9M = 33;
    public static final Integer SUMMARY_GAME_COUNT_OF_MISS_6M = 34;
    public static final Integer SUMMARY_GAME_COUNT_OF_MISS_7M = 35;
    public static final Integer SUMMARY_GAME_COUNT_OF_MISS_9M = 36;
    public static final Integer SUMMARY_GAME_COUNT_OF_GOALKEEPER_BREJK = 37;
    public static final Integer SUMMARY_GAME_COUNT_OF_GOALKEEPER_WING = 38;
    public static final Integer SUMMARY_GAME_COUNT_OF_GOALKEEPER_6M = 39;
    public static final Integer SUMMARY_GAME_COUNT_OF_GOALKEEPER_7M = 40;
    public static final Integer SUMMARY_GAME_COUNT_OF_GOALKEEPER_9M = 41;
    public static final Integer SUMMARY_GAME_PREDICTION_OF_SHOTS = 42;
    public static final Integer SUMMARY_GAME_PREDICTION_OF_SHOTS_BREJK = 43;
    public static final Integer SUMMARY_GAME_PREDICTION_OF_SHOTS_WING = 44;
    public static final Integer SUMMARY_GAME_PREDICTION_OF_SHOTS_6M = 45;
    public static final Integer SUMMARY_GAME_PREDICTION_OF_SHOTS_7M = 46;
    public static final Integer SUMMARY_GAME_PREDICTION_OF_SHOTS_9M = 47;
    public static final Integer SUMMARY_GAME_PREDICTION_OF_FAULS_SHOTS = 48;
    public static final Integer SUMMARY_COUNT_GAME_PLAYED_HOME = 49;
    public static final Integer SUMMARY_COUNT_GAME_PLAYED_OUT = 50;
    public static final Integer SUMMARY_MATCH_TIME = 51;
    public static final Integer SUMMARY_TIME_IN_OFENSIVE = 52;
    public static final Integer SUMMARY_TIME_IN_DEFENSIVE = 53;
    public static final Integer SUMMARY_VALUES_CHANGE = 54;
    public static final Integer SUMMARY_GAME_TURNAMENT_PK = 55;


//    public static final Integer LINEUP = "LineUp";       //0
//    public static final Integer LINEUPPK = "LineUpPK";   //1
//    public static final Integer TURNAMENTLINEUPSPK = "TurnamentLineUpsPK";     //2
//
//    public static final Integer MISSSHOTSOPPONENT = "MissShotsOpponent";
//    public static final Integer FAULOPPONENT = "FaulOpponent";
//    public static final Integer DATE = "Date";
//    public static final Integer OPPONENT_PK = "Opponent_PK";
//    public static final Integer TURNAMENTOPPONENTSPK = "TurnamentOpponentsPK";     //4
//
//    public static final Integer TURNAMENTNAME = "TurnamentName";
//    public static final Integer TURNAMENTPK = "TurnamentPK";
//

    //    public static final Integer COUNT_OF_MONITORING_PLAYERS = "count_of_monitoring_players"; //0
//    public static final Integer HOWOFTENRECORDGAME = "HowOftenRecordGame";           //1
//    public static final Integer NAME_OF_MONITORING_TEAM = "name_of_monitoring_team"; //2
//    public static final Integer GAME_TIME = "game_time";                             //3
//    public static final Integer COUNT_OF_PERIODS = "count_of_periods";               //4
//    public static final Integer PLAYER_ONE = "player_one";                           //5
//    public static final Integer PLAYER_TWO = "player_two";                           //6
//    public static final Integer PLAYER_THREE = "player_three";                       //7
//    public static final Integer PLAYER_FOUR = "player_four";                         //8
//    public static final Integer PLAYER_FIVE = "player_five";                         //9
//    public static final Integer PLAYER_SIX = "player_six";                           //10
//    public static final Integer GOALKEEPER = "goalkeeper";                           //11
//    public static final Integer OPTION_GOAL_ON_TARGET = "option_goal_on_target";     //12
//    public static final Integer OPTION_SHOT_MISS = "option_shot_miss";               //13
//    public static final Integer OPTION_SHOT_GOALKEEPER = "option_shot_goalkeeper";   //14
//    public static final Integer OPTION_MISS_BALL = "option_miss_ball";               //15
//    public static final Integer OPTION_REACH_FAUL_SHOT = "option_reach_faul_shot";   //16
//    public static final Integer OPTION_PLUS = "option_plus";                         //17
//    public static final Integer OPTION_MINUS = "option_minus";                       //18
//    public static final Integer OPTION_FAUL = "option_faul";                         //19
//    public static final Integer OPTION_YELLOW_CARD = "option_yellow_card";           //20
//    public static final Integer OPTION_RED_CARD = "option_red_card";                 //21
//    public static final Integer OPTION_REACH_BALL = "reach_ball";                    //22
//    public static final Integer OPTION_PLAYERS_TIME_ON_PLAYGROUND = "option_players_time_on_playground"; //23
//    public static final Integer ORDER_PK = "order_pk";                               //24
//    public static final Integer TURNAMENTGAMEOPTIONSPK = "TurnamentGameOptionsPK";   //25
//
    public static String DATE_TIME_FOR_HISTORY = "";

}